from sqlalchemy.orm import Session
from models.ticket import Ticket
from typing import List, Optional


# =========================
# Create
# =========================
def create_ticket(db: Session, ticket_data: dict) -> Ticket:
    ticket = Ticket(**ticket_data)
    db.add(ticket)
    db.flush()              # ensures ID is written
    db.refresh(ticket)      # loads autogenerated fields (purchase_date)
    return ticket


# =========================
# Read
# =========================
def get_ticket_by_id(db: Session, ticket_id: str) -> Optional[Ticket]:
    return db.query(Ticket).filter(Ticket.id == ticket_id).first()


def get_ticket_by_email(db: Session, email: str) -> Optional[Ticket]:
    return db.query(Ticket).filter(Ticket.email == email).first()


def get_ticket_by_phone(db: Session, phone: str) -> Optional[Ticket]:
    return db.query(Ticket).filter(Ticket.phone == phone).first()


def get_tickets_by_original_tx_ref(db: Session, tx_ref: str) -> List[Ticket]:
    """
    Fetch ALL tickets created from the same transaction.
    Matches tx_ref-ticketId pattern.
    """
    return (
        db.query(Ticket)
        .filter(Ticket.tx_ref.like(f"{tx_ref}%"))
        .order_by(Ticket.purchase_date.asc())
        .all()
    )


def transaction_already_processed(db: Session, tx_ref: str) -> bool:
    """
    Used to prevent duplicate ticket creation.
    """
    return (
        db.query(Ticket)
        .filter(Ticket.tx_ref.like(f"{tx_ref}%"))
        .first()
        is not None
    )


def get_all_tickets(db: Session) -> List[Ticket]:
    return (
        db.query(Ticket)
        .order_by(Ticket.purchase_date.desc())
        .all()
    )


# =========================
# Update
# =========================
def mark_ticket_checked_in(db: Session, ticket: Ticket) -> Ticket:
    ticket.is_checked_in = True
    db.commit()
    db.refresh(ticket)
    return ticket


# =========================
# Delete
# =========================
def delete_ticket(db: Session, ticket: Ticket):
    db.delete(ticket)
    db.commit()
